README.md
lib/gds-components/button/Button.tsx
lib/timetable-form/Form.tsx

Add button component missed in original PR

SOW-24: add GDS button component

---

README.md

Update the description for the `build:cdn` script

SOW-24: fix CDN typo

---

lib/constants.ts
lib/timetable-form/Form.test.tsx
lib/timetable-form/Form.tsx
lib/types/timetable.ts
lib/utils/timetable.test.ts
lib/utils/timetable.ts

Add editing to the timetable form, following the data structure approach of invalidating old rows.
This only addresses editing the events, I'll look into editing the plan data separately.

SOW-24: Implement event editing in timetable form

---

cdn-vite.config.ts

Adding the favicon for the form wrapper app also included it in the CDN build, which isn't needed. Since we're already manually copying the fonts (and for now, I'm keeping that step since we're rewriting the URLs), we can just exclude the `public` directory from the build.

SOW-24: exclude favicon from CDN build

---

cdn-vite.config.ts

Spotted this during some investigation around styling the CDN component. Currently we don't have any CSS modules for this component but without this option in the build, it wouldn't be possible to import kebab case classes as camel case.

SOW-24: fix CSS modules in CDN build

---

lib/timetable-form/Form.test.tsx
lib/timetable-visualisation/PlanViewer.tsx
lib/timetable-visualisation/Visualisation.test.tsx

Cleaning up console warnings and errors in tests:
- `act` errors from the testing library
- Old React class methods from the autocomplete component
I looked into the warnings seen at the beginning of the tests but setting the `esModuleInterop` caused errors, so I decided to leave for now

SOW-24: cleanup test console errors and warnings

---

README.md

Now that the form is a full static application (not just a component), reword the README to avoid calling the repo a component library

SOW-24: update readme to remove reference to component library

---

lib/timetable-visualisation/PlanViewer.tsx

Use event names in the visualisation and preview instead of the codes

SOW-24: use event names in visualisation

---

lib/stories/FormStage.stories.tsx
lib/timetable-form/Form.test.tsx
lib/timetable-form/pages/LPAPage.test.tsx
lib/timetable-form/pages/StagePage.test.tsx
lib/timetable-form/pages/StagePage.tsx

- move FormStage to pages/ and rename to StagePage
- add unit tests

SOW-24: move stage to pages and add tests

---

package.json

Accidentally reverted the changes I made to the `package.json` in my last PR and didn't noticed

SOW-24: add missing script changes for builds

---

src/main.tsx

Browser router doesn't work in GitHub pages, you'll get a 404 on any non-root page because it's looking for an HTML page with that name. There's no way around this as we can't configure to service the index file at every path. The solution for this is to switch to a hash router, which is a very minor change:
`http://localhost:5173/local-plans-timetable/title-of-local-plan` -> `http://localhost:5173/local-plans-timetable#/title-of-local-plan`

SOW-24: switch to hash router to support GitHub Pages

---

lib/constants.ts
src/pages/stage-page/StagePage.test.tsx

Exclude status events and time table updated from the default events created at the start of the journey. There are a few things that we can start to clean up once we've aligned the visualisation to the designs:
- We won't need the event key to name mapping anymore, this is the responsibility of our "stages"
- We won't need to sort the events any more because we won't be relying on their order
- We will still need to filter out invalidated events

SOW-24: exclude some events from the defaults

---

src/pages/export-page/ExportPage.tsx
src/pages/upload-timetable-page/UploadTimetablePage.tsx

The `timetable-updated` event was never being updated on edit because there was no reference match in the events from the form. This PR:
- Filters out the old event from the form on upload (since this event isn't being edited, the diffing would decide it hadn't changed)
- When creating the new event, use the existing reference if there is one to make sure the old event is invalidated

SOW-24: ensure timetable updated time is updated on edit

---

lib/utils/timetable.test.ts
lib/utils/timetable.ts

Only using `\n` for the CSV line separator doesn't support UNIX systems (this issue was noticed on a Mac)

SOW-24: support UNIX systems for CSV files

---

lib/gds-components/character-count/CharacterCount.test.tsx
lib/gds-components/character-count/CharacterCount.tsx
lib/gds-components/character-count/__snapshots__/CharacterCount.test.tsx.snap
lib/gds-components/text-area/TextArea.tsx
lib/gds-components/text-input/TextInput.tsx
src/main.css
src/pages/description-page/DescriptionPage.tsx
src/pages/stage-page/StagePage.tsx
src/pages/status-change-event-page/StatusChangeEventPage.tsx
src/pages/title-page/TitlePage.tsx

Replace the static message with a dynamic character count. Also renames the prop to `characterLimit` now that only the number is being passed down, rather than all the text.

SOW-24: dynamic textarea remaining character count 

---

src/main.tsx
src/pages/create-timetable-page/CreateTimetablePage.tsx
src/pages/how-to-publish-page/HowToPublishPage.tsx
src/pages/index.ts
src/pages/nav-page-wrapper/NavPageWrapper.module.css
src/pages/nav-page-wrapper/NavPageWrapper.tsx
src/routes/routes.ts

This PR add the how to publish a timetable page and also extracts the nav into its own component. A couple of things to note:
- I've skipped the link that should appear after the first set of bullet points
- This would link to a real example of the visualisation, I'll create a ticket for this to prioritise
- 3 of the links point to content pages that don't exist yet, we'll add those in the relevant tickets
- We've made an assumption on where the CSV info link should point, I'll make a point to confirm this but we've got the go ahead to put this in for now

SOW-24: how to publish a timetable

---

lib/timetable-visualisation/PlanViewer.tsx
lib/utils/timetable.test.ts
lib/utils/timetable.ts

The event statuses are now driven by the last updated date instead of the current date

SOW-24: use lastUpdatedDate to derive event statuses

---

lib/gds-components/index.ts
lib/gds-components/tag/Tag.tsx
lib/timetable-visualisation/PlanViewer.tsx
lib/utils/timetable.test.ts
lib/utils/timetable.ts

Changes to the behaviour of what status tags show in what situation after speaking to Emma A.
**General note:** The `timetable-updated` event is captured as a full ISO string (with the time) but when we're using it to calculate the tags, we should only be using the date portion
These are the scenarios discussed with Emma, split into events that are part of a stage and individual date events (i.e. not part of a stage). We broadly agreed that we'll only show a tag if all the information is present, i.e. all dates that were asked for are provided.
**Start event only**
- No event date given -> No tag
- Event date is before last updated date -> `FINISHED`
- Event date is the same as last updated date -> `FINISHED`
- Event date is after last updated date -> `NOT STARTED`
**Start event and end …

SOW-24: refine status tag behaviour

---

assets/development-plan.csv
assets/timetable.csv
lib/utils/timetable.test.ts
lib/utils/timetable.ts

- convert object keys to kebab-case when generating the CSV headers
- convert CSV headers to camelCase when creating object keys
- update assets files to have CSV headers in kebab case

SOW-24: use kebab-case for CSV headers

---

lib/gds-components/radios/Radios.tsx
src/pages/status-change-event-page/status-change-event-validation.ts
src/pages/update-timetable-status-page/update-timetable-status-validation.ts

- Reword the error messages
- "Answer is required" -> "Select yes if you need to update the status of your Local Plan timetable"
- "Status is required" -> "Select the status of your Local Plan"
- Adjust the location of the error message relative to the radio options

SOW-24: radio errors

---

src/pages/publish-online-guidance/PublishOnlineGuidancePage.tsx

Small copy change, the both tags can go in either the `head` or `body`, the instructions should reflect this

SOW-24: reword instructions for importing CDN files

---

lib/gds-components/index.ts
src/context/FormContext.tsx
src/main.tsx
src/pages/FormPageHoc.tsx
src/pages/status-change-event-page/StatusChangeEventPage.tsx
src/pages/update-dates-page/UpdateDatesPage.tsx
src/pages/update-dates-page/update-dates-validation.ts
src/pages/update-timetable-status-page/UpdateTimetableStatusPage.tsx
src/pages/use-sequence.ts
src/routes/routes.ts

Add a new page in the edit journey to ask if a user wants to update their dates:
- If yes, continue as before
- If no, skip straight to the export page
Also added basic validation in line with the equivalent page for timetable status.

SOW-24: add routing page for updating dates

---

lib/gds-components/button/Button.tsx
lib/snippet/Snippet.tsx
lib/snippet/snippet.module.css

- use CodeBlock instead of CopyBlock (only difference between the 2 components is the copy button)
- add custom copy button
- add custom style for copy button

SOW-24: add text to copy button

---

.github/workflows/lint-and-test.yml
.github/workflows/pr-check.yml
README.md
package.json

Add type checks to the PR workflow for both build steps so we know if they'll fail before we merge

SOW-24: add a type check step to PR workflow
