README.md
jest.config.ts
lib/timetable-form/Form.test.tsx
package-lock.json
package.json
tests/mocks/fileMock.js
vite.config.ts

Sets up Jest and React testing library
Add a single unit test

SOW-24: Add jest testing to project

---

lib/timetable-form/Form.test.tsx
lib/timetable-form/Form.tsx
lib/timetable-form/styles.module.css
vite.config.ts

- Add fields for LPA name and date for each stage

SOW-24: Create basic form

---

package-lock.json
package.json

Bump to latest beta version of `@storybook/react-vite` to fix GH Pages deployment

SOW-24: bump @storybook/react-vite

---

assets/timetable.csv
assets/timetableHeader.csv
lib/main.ts
lib/stories/Visualisation.stories.ts
lib/timetable-visualisation/Visualisation.test.tsx
lib/timetable-visualisation/Visualisation.tsx
lib/types/timetable.ts
lib/utils/timetable.ts
package-lock.json
package.json

- Added Visualisation component with story
- Added 2 CSV files for example story

SOW-24: Visualisation Component

---

lib/constants.ts
lib/timetable-form/Form.test.tsx
lib/timetable-form/Form.tsx
lib/timetable-visualisation/PlanPreview.tsx
lib/timetable-visualisation/PlanViewer.tsx
lib/timetable-visualisation/Visualisation.test.tsx
lib/timetable-visualisation/Visualisation.tsx
lib/types/timetable.ts
lib/utils/timetable.ts

- add Preview component
- use Preview in Form and Visualisation components

SOW-24: Preview component

---

lib/constants.ts
lib/timetable-form/Form.test.tsx
lib/timetable-form/Form.tsx
lib/types/timetable.ts
lib/utils/timetable.ts

Added second button to end of form for timetable header download

SOW 24: add second csv download

---

assets/timetable.csv
assets/timetableHeader.csv
lib/constants.ts
lib/gds-components/date-input/DateInput.test.tsx
lib/gds-components/date-input/DateInput.tsx
lib/gds-components/file-upload/FileUpload.test.tsx
lib/gds-components/file-upload/FileUpload.tsx
lib/gds-components/file-upload/__snapshots__/FileUpload.test.tsx.snap
lib/gds-components/index.ts
lib/timetable-form/Form.tsx
lib/timetable-visualisation/PlanViewer.tsx
lib/types/timetable.ts
lib/utils/timetable.ts

- new component for file upload
- add FileUpload components to Form

SOW-24: populate form with CSV files

---

.github/workflows/deploy.yml
.gitignore
README.md
index.html
lib-vite.config.ts
package.json
src/App.tsx
src/main.tsx
src/vite-env.d.ts
vite.config.ts

- add App containing Form
- add vite-config for building app

SOW-24: wrap form in app - WIP

---

.gitignore
.storybook/main.ts
README.md
package-lock.json
package.json
scripts/cdn-post-build.cjs
scripts/copy-fonts.cjs
scripts/wrapper-pre-build.cjs

Fix issues where the GDS fonts weren't being correctly imported

SOW-24: apply GDS fonts

---

lib/constants.ts
lib/timetable-form/Form.test.tsx
lib/timetable-form/Form.tsx
lib/timetable-visualisation/PlanViewer.tsx
lib/timetable-visualisation/Visualisation.tsx
lib/types/timetable.ts
lib/utils/timetable.test.ts
lib/utils/timetable.ts

Follow-on from #20, this adds basic edit support for the development plan

SOW-24: development plan editing

---

assets/timetable.csv

Update the example events CSV to use event codes instead of names

SOW-24: update event names to codes in example file

---

lib/gds-components/button/Button.tsx
lib/gds-components/date-input/DateInput.tsx
lib/gds-components/error-summary/ErrorSummary.tsx
lib/gds-components/index.ts
lib/timetable-form/Form.test.tsx
lib/timetable-form/Form.tsx
lib/timetable-form/useValidation.tsx
lib/validation/index.ts
package-lock.json
package.json

- validate field on form using schema
- display validation errors in error summary
- display error message on DateField
Custom error messages following [GDS guidance](https://design-system.service.gov.uk/components/date-input/)

SOW-24: establish validation

---

lib/gds-components/date-input/DateInput.test.tsx
lib/gds-components/date-input/DateInput.tsx
lib/gds-components/date-input/__snapshots__/DateInput.test.tsx.snap
lib/timetable-form/Form.test.tsx

Adds leading zero top the month of the DateInput on blur

SOW 24: add leading zero to month in DateInput

---

lib/stories/LPAPage.stories.ts
lib/timetable-form/pages/LPAPage.test.tsx
lib/timetable-form/pages/LPAPage.tsx

- add component for "What is your Local Authority?" Page
- add story for new component

SOW-24: lpa page

---

lib/constants.ts
lib/gds-components/date-input/DateInput.tsx
lib/gds-components/date-input/__snapshots__/DateInput.test.tsx.snap
lib/gds-components/text-area/TextArea.tsx
lib/gds-components/text-area/__snapshots__/TextArea.test.tsx.snap
lib/timetable-visualisation/Visualisation.test.tsx
src/main.tsx
src/pages/stage-page/StagePage.test.tsx
src/pages/stages.tsx
src/pages/use-sequence.tsx
src/routes/routes.ts

- update events list
- add missing stages
- minor tweaks to match design

SOW-24: edit event list and add new stages

---

src/main.tsx

Fix the casing in the import not matching the filename

SOW-24: fix import casing

---

lib/gds-components/file-upload/FileUpload.tsx
lib/gds-components/file-upload/__snapshots__/FileUpload.test.tsx.snap
src/context/FormContext.tsx
src/main.tsx
src/pages/create-timetable-page/CreateTimetablePage.tsx
src/pages/index.ts
src/pages/upload-timetable-page/UploadTimetablePage.tsx
src/routes/routes.ts

- add page for uploading CSV files
- add state for loaded data
- new page is not part of the sequence yet

SOW-24: upload CSV page

---

lib/timetable-visualisation/PlanViewer.tsx
lib/utils/timetable.ts
src/main.tsx
src/pages/FormPageHoc.tsx
src/pages/LPA-page/LPAPage.tsx
src/pages/description-page/DescriptionPage.tsx
src/pages/export-page/ExportPage.module.css
src/pages/export-page/ExportPage.test.tsx
src/pages/export-page/ExportPage.tsx
src/pages/publish-LDS-page/PublishLDSPage.tsx
src/pages/stage-page/StagePage.tsx
src/pages/title-page/TitlePage.tsx
src/pages/use-sequence.ts
src/routes/routes.ts

Add final page to export and preview timetable data

SOW-24: export timetable

---

src/pages/stages.tsx

Add the links to the relevant regulations (opening in a new tab)

SOW-24: add links for regulations

---

lib/gds-components/date-input/DateInput.tsx
lib/gds-components/date-input/__snapshots__/DateInput.test.tsx.snap
lib/gds-components/footer/Footer.tsx
src/pages/FormPageHoc.tsx
src/pages/export-page/ExportPage.tsx
src/pages/form-page.module.css

Small issues addressed:
- Added day to date input hint when applicable
- Removed extra padding from form pages
- Added missing space in footer text
- Fixed style of link on export page

SOW-24: post demo cleanup

---

src/routes/Page.tsx
src/routes/ScrollToTop.ts

Moves view to the top when moving between pages

SOW-24: scroll to top of new page

---

src/pages/export-page/ExportPage.tsx

SOW-24: fix typo

---

lib/utils/timetable.ts
src/pages/export-page/ExportPage.tsx
src/pages/upload-timetable-page/UploadTimetablePage.tsx

Use Blob data URL for download and the `csvToJson` library for upload

SOW-24: support Mac for CSV upload and download

---

src/pages/update-timetable-status-page/UpdateTimetableStatusPage.tsx

SOW-24: add missing text to update status page

---

src/main.tsx
src/pages/how-to-publish-page/HowToPublishPage.tsx
src/pages/index.ts
src/pages/visualisation-example/VisualisationExamplePage.tsx
src/routes/routes.ts

- add new route for "visualisation example" page
- link "how to publish" page and "visualisation example" page

SOW-24: visualisation example page

---

lib/autocomplete/Autocomplete.tsx
src/main.tsx
src/pages/LPA-page/LPAPage.tsx
src/pages/LPA-page/lpa-validation.ts

Add validation to LPA page making the LPA field required

SOW-24: Validate LPA

---

lib/gds-components/file-upload/FileUpload.test.tsx
lib/gds-components/file-upload/FileUpload.tsx
src/main.tsx
src/pages/FormPageHoc.tsx
src/pages/upload-timetable-page/UploadTimetablePage.tsx
src/pages/upload-timetable-page/validate-upload-timetable-page.ts

PR to check if both CSV files are uploaded.

SOW-24: File upload page validation

---

src/pages/how-to-publish-page/HowToPublishPage.tsx

SOW-24: CSV info link opens in new tab

---

src/pages/nav-page-wrapper/NavPageWrapper.tsx
src/pages/visualisation-example/VisualisationExamplePage.tsx
src/routes/routes.ts

- add link to visualisation in navbar 
- add header and paragraph to visualisation example page

SOW-24 add link to visualisation example

---

src/pages/publish-online-guidence/code-snippets/GuidencePageExampleCodeSnippet.tsx
src/pages/publish-online-guidence/code-snippets/GuidencePageStep4CodeSnippets.tsx

SOW-24: fix snippets

---

lib/gds-components/tag/Tag.tsx
lib/utils/timetable.test.ts
lib/utils/timetable.ts
src/pages/export-page/ExportPage.tsx

align the tag styling with what is on the govuk styling page.
add correct link for guidance page on the export timetable page

SOW-24: align tag component with govuk tag component styling

---

lib/snippet/snippet.module.css

Added margin bottom to snippets to match design

SOW-24: more margin-bottom for snippet

---

lib/gds-components/phase-banner/PhaseBanner.tsx

SOW-24: edit banner text

---

lib/gds-components/text-area/TextArea.tsx
src/pages/stage-page/StagePage.tsx
src/pages/status-change-event-page/StatusChangeEventPage.tsx

Add a hint for textarea components (used for the additional information inputs)

SOW-24: add text area hint

---

src/pages/event-schema.ts
src/pages/stage-page/StagePage.test.tsx
src/pages/stage-page/StagePage.tsx
src/pages/status-change-event-page/StatusChangeEventPage.tsx

- raised character limit for all stages "additional information"

SOW-24: raise character limit for notes to 200

---

.github/workflows/pr-check.yml

Forgot to rename the workflow (just renamed the file)

SOW-24: rename PR check workflow
